### ISSUE TITLE
get auto-properties are converted to functions.

### ISSUE THREAD

**Issue by MicahZoltu** [YoloDev/babel-dts-generator#16]
https://github.com/aurelia/router/blob/master/src/navigation-context.js#L21

``` js
get nextInstructions() {
    return ...;
}
```

converts to
https://github.com/aurelia/router/blob/master/dist/index.d.ts#L69

``` ts
nextInstructions(): any;
```

It should convert to `nextInstructions: any;` (no parenthesis).

**Comment by Alxandr** [comment]
This might unfortunately not be doable. The problem is that the AST generated by babel removes some information that would normally be required to distinguish different constructs. For instance, the flollowing two pieces of code generates the same AST:

``` typescript
// first variant
interface IFoo {
  foo(): void;
}

// second variant
interface IFoo {
  foo: () => void;
}
```

Now, I'm not saying it's the same for auto-properties, as I would have to try it out and see what AST it generates, but given that the output is what it is, my guess is it might not be doable.

**Comment by MicahZoltu** [comment]
In the interface case, both compile to the same thing I believe.  In this case, a getter compiles to something different.

ES6 input

``` js
class Foo {
  get myGetter() {}

  myMethod() {}
}
```

ES5 output

``` js
var Foo = (function () {
  function Foo() {
    _classCallCheck(this, Foo);
  }

  _createClass(Foo, [{
    key: "myMethod",
    value: function myMethod() {}
  }, {
    key: "myGetter",
    get: function () {}
  }]);

  return Foo;
})();
```

This implies to me that the AST stores enough information to identify the difference.  That being said, I haven't looked at Babel's AST so it may not be trivial to extract out the difference.

**Comment by Alxandr** [comment]
Good point. Will look into it. Though, I'm on vacation (for the foreseeable future, with parents) so I can't really tell when that'll be.
