### ISSUE TITLE
Convention for Private Members

### ISSUE THREAD

**Issue by EisenbergEffect** [YoloDev/babel-dts-generator#9]
Since JavaScript doesn't have `private` members yet, perhaps an optional setting on the generator could be added based on a convention. For example, have the generator exclude all members that begin with an `_`.

**Comment by cmichaelgraham** [comment]
I'd like to take a shot at this.  I'll start down the path and see if I can implement it.  @Alxandr - will submit for your review and feedback when ready :+1:

**Comment by Alxandr** [comment]
Add a regex to the option object. Default it to ^_.*

Match against any member (if it is non-null).

**Comment by Alxandr** [comment]
So, I've thought about this a bit, and here are a simple spec (if you want to take a crack at it @cmichaelgraham, otherwise I can probably do it myself, though assigning you for now since you stated you wanted it).

First of, add a member to the options, name it something akin to `ignoreMembers`, and do the following with it:
1. If it's `null` (literally, not undefined), don't ignore any members.
2. If it's a string, convert it to a regex, and treat it as such.
3. If it's a regex, match it against members. If it's a match, ignore them.
4. If it's a function, run it against the member-name and return type string. If it returns truthy, ignore the member.

**Comment by cmichaelgraham** [comment]
looks great :+1:

**Comment by Alxandr** [comment]
I also need to get some tests in eventually... Features like this needs to be unit-tested.

**Comment by cmichaelgraham** [comment]
this can be closed now :+1:
